baseURL = "https://hanuliakova.me/"
languageCode = "en-us"
title = "Katarína Hanuliaková"
theme = "anatole"
publishdir = "docs"
contentDir = "content"
disableHugoGeneratorInject = true

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"


[params]
title = "Katka Hanuliaková"
author = "Katarína Hanuliaková"
description = "3D design, video and animation"
profilePicture = "/images/P1020203c.jpg"

  [[params.socialIcons]]
  icon = "fas fa-envelope"
  title = "e-mail"
  url = "mailto:katula.h@gmail.com"

  [[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://cz.linkedin.com/in/katarinahanuliakova"

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
